# Generated by Django 4.2.5 on 2023-09-30 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='bikeId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.bikeupload'),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='bshId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.bookssportshobbiesupload'),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='carId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.carupload'),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='commId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.commupload'),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='elecId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.electronicappliancesupload'),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='fashionId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.fashionupload'),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='furnitureId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.furnitureupload'),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='jobId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.jobupload'),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='mobileId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.mobileupload'),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='petId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.petupload'),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='propertyId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.propertyupload'),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='serviceId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.serviceupload'),
        ),
    ]
