# Generated by Django 4.2.5 on 2023-10-01 18:28

import backend.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_favorite_bikeid_alter_favorite_bshid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Barter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flipperUser', models.CharField(default='', max_length=200)),
                ('barterTitle', models.CharField(default='', max_length=200)),
                ('barterDescription', models.CharField(default='', max_length=2000000)),
                ('barterRequirement', models.CharField(default='', max_length=2000000)),
                ('barterLocation', models.CharField(default='', max_length=200)),
                ('barterImage', backend.models.FileField(blank=True, default='', upload_to='BarterImages/')),
            ],
        ),
    ]
