# Generated by Django 4.2.5 on 2023-10-03 01:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_barter'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteBarter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flipperUser', models.CharField(default='', max_length=200)),
                ('barterId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.barter')),
            ],
        ),
    ]
