# Generated by Django 4.2.5 on 2023-10-09 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='auctionTime',
            field=models.TimeField(),
        ),
    ]
